Allow variable substitution with ${workspaceFolder} in libPaths config.
Sebbia/vscode-jsonnet-ng pull request #2
Opened 2021-09-09 04:58 UTC by drumlab

This allows us to add workspace relative paths to libPaths.

2021-11-01 03:20 UTC, drumlab commented
@navrocky Hello, is this something can be accepted? Thanks!

2021-11-08 19:07 UTC, ProfMoo commented
@navrocky This would be very helpful for me. Would love if this could be reviewed and merged.

2021-11-13 09:43 UTC, BronzeDeer commented
I'm not sure if hardcoding the single variable (especially exactly and not allowing for whitespace differences) etc is the best reason, wouldn't a better solution be to put the current directory always at workspace root instead of next to the file? Currently, static analysis seems to already  use that as current path and only fumbles when running a file for preview.
(Try it, put the correct relative libPath in, and you will only get runtime errors, but if you remove it you will get many "not found" warnings as well)

2021-11-20 14:01 UTC, navrocky requested changes

2021-11-20 14:01 UTC, navrocky commented on server/server.ts
> +  console.log(change);
You need to remove console.log

2021-12-27 06:36 UTC, drumlab commented on server/server.ts
> +  console.log(change);
Done.

2021-12-27 06:37 UTC, drumlab commented
I somehow missed the review earlier. Thanks!

2021-12-28 22:09 UTC, merged

2022-01-11 14:56 UTC, ProfMoo commented
@navrocky Thanks for the merge! Can we get a new version tagged and released? I want to update my version used in VSCode

2022-01-13 14:21 UTC, navrocky commented
> @navrocky Thanks for the merge! Can we get a new version tagged and released? I want to update my version used in VSCode

Just publish it as 1.2.1